version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-net

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-net
    volumes:
        - ./backend/client_secret.json:/app/client_secret.json:ro

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
