services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-net

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./secrets/.env
    depends_on:
      - db
    networks:
      - app-net
    volumes:
      - ./secrets:/secrets:ro
      - ./secrets/client_secret.json:/app/client_secret.json:ro

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./secrets/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/scripts
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
