version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
      - app-net

  backend:
    build:
      context: ./backend
    env_file:
      - ./secrets/.env
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:15-alpine
    env_file:
      - ./secrets/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    name: whenly_app-net
    external: false
