version: '3.9'

services:
  web:
    build: .
    container_name: flask-calendar-app
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - .:/app  # Mount code for live editing
      - ./client_secret.json:/app/client_secret.json  # Inject secrets securely
    restart: unless-stopped
